#Good Graphs are the best way to present findings 
#there are inbuilt graphs(Bae Graphs) in R and addins from lattice and ggplot2 packages 
#Graphics are used in statistics primarily for two reasons: exploratory data analysis (EDA)
#and presenting results. Both are incredibly important but must be targeted to
#different audiences.
#Base Graphs 
#While base graphs can be beautiful
#creations, we recommend spending the most time learning about ggplot2 
#This section is here for completeness and because base graphics are just needed,
#especially for modifying the plots generated by other functions.
#Note that the inbuilt R datasets are smaller than those in ggplot2 package 


#Example using Diamonds dataset of ggplot2
library(ggplot2)
data(diamonds)
head(diamonds)


#BASE HISTOGRAMS FOR UNIVARIATE DATA 
hist(diamonds$carat, main="Carat Histogram", xlab="Carat")

#main is the title and xlab is for the x-Axis label 
#Histograms break the data into buckets and the heights of the bars represent
#the number of observations that fall into each bucket.

#BASE SCATTER PLOT for Bivariate Data 
#It is frequently good to see two variables in comparison with each other;
#Every point represents an observation in two variables where the-axis
#represents one variable and the-axis another. We will plot the price of diamonds against
#the carat using formula notation.
plot(price ~ carat, data=diamonds)


#Boxplots 
boxplot(diamonds$carat)
#The idea behind the boxplot is that the thick middleline represents the 
#median and the box is bounded by the first and third quartiles.


#USING GGPLOT AND LATTICE,PACKAGES THAT WERE MADE TO MAKE GRAPHING EASIER

#USING GGPLOT 
#After initializing the object, we add layers using the +
#symbol. To start, we will just discuss geometric layers such as points, lines and
#histograms. They are included using functions like geom_point, geom_line and
#geom_histogram. . These functions take multiple arguments, the most important being
#which variable in the data gets mapped to which axis or other aesthetic using
#aes.
ggplot(data=diamonds) + geom_histogram(aes(x=carat))


#Density plot 
#Density plots show the probability
#of observations falling within a sliding window along the variable of interest
#we use geom_density 
#fill argument is used to make the whole graph takeup
#the specified color (place outside aes)
ggplot(data=diamonds) + geom_density(aes(x=carat), fill="grey50")

#difference to note 
#Histograms are more of a discrete
#measurement, while density plots are more of a continuous measurement.

#USING AES inside ggplot()
# we use ggplot to initialize the object, but this time we include aes inside the
#ggplot call instead of using it in the geom
ggplot(diamonds, aes(x=carat, y=price)) + geom_point()

#we can save these basics of the ggplot to a variable 
g <- ggplot(diamonds, aes(x=carat,y=price))
#Going forward we can add any layer to g. Running g + geom_point() would
#re-create the graph shown above

#Coloring 
g + geom_point(aes(color=color))

#Notice that we set color=color inside aes. This is because the designated color will
#be determined by the data. Also see that a legend was automatically generated.

#Data in the the plat can be faceted using FacetGrid, facetwrap
#facet_grid. facet_wrap takes the levels of
#one variable, cuts up the underlying data according to them, makes a separate 
#pane for each set and arranges them to fit in the plot


#USING FACET WRAP 
g + geom_point(aes(color=color)) + facet_wrap(~color)

#USING A FACET GRID

g + geom_point(aes(color=color)) + facet_grid(cut~clarity)

##Faceting also works with histograms or any other geom,
ggplot(diamonds, aes(x=carat)) + geom_histogram() + facet_wrap(~color)

#GGPLOT BOXPLOTS 
ggplot(diamonds, aes(y=carat, x=1)) + geom_boxplot()
#Even though it is one-dimensional,using only a aesthetic, there needs
#to be some x aesthetic,so we will use 1.

#MULTIPLE BOXPLOTS 
ggplot(diamonds, aes(y=carat, x=cut)) + geom_boxplot()


#USING VIOLINPLOTS INSTEAD
ggplot(diamonds, aes(y=carat, x=cut)) + geom_violin()
#Violin plots are similar to boxplots except that the boxes are curved, giving a sense of
#the density of the data. This provides more information than the straight sides of
#ordinary boxplots.

#POSITIONING OF LAYERS may differ
ggplot(diamonds, aes(y=carat, x=cut)) + geom_point() + geom_violin()
ggplot(diamonds, aes(y=carat, x=cut)) + geom_violin() + geom_point()

#Notice that the order of the layers matters. In the graph on the left, the points 
#are underneath the violins, while in the graph on the right, the points are on 
#top of the violins.

#GGPLOT LINE GRAPHS 

#Line charts are often used when one variable has a certain continuity, but that is not always
#necessary because there is often a good reason to use a line with categorical data
ggplot(economics, aes(x=date,y=pop)) + geom_line()
#This worked , but always make sure you add the group aesthetic
#aes(group=1)

#TASK

#DISPLAYING METRICS OVER  THE COURSE OF A YEAR  FOR MANY YEARS 
#we shall use whickams LUBRIDATE PACKAGE to prepare the economics data
#the package has convenient functions for manipulating dates
#We need to create two new variables,
#year and month. To simplify things we will subset the data to include only years starting
#with 2000.

#Load the lubridate package 
library(lubridate)

#create  year and month variables
economics$year <- year(economics$date)

# the label argument to month means that the result should be the
# names of the month instead of the number
economics$month <- month(economics$date, label=TRUE)

#SUBSETTING THE DATA  USIng which function 
econ2000 <- economics[which(economics$year >= 2000),]

#LOADING SCALES PACKAGE FOR BETTER AXIS FORMATTING 
library(scales)

#BUILDING THE FOUNDATION OF THE PLOT 
g1 <- ggplot(econ2000, aes(x=month, y=pop))

#Adding lines color coded and grouped by layer 
#the group aesthetics breaks the data into separate groups 
g1 <- g1 + geom_line(aes(color=factor(year), group=year))

#Name the legend year 
g1 <- g1 + scale_color_discrete(name="Year")
#Format the y axis
g1 <- g1 + scale_y_continuous(labels=comma)

#Add title and axis labels 
g1 <- g1 + labs(title="Population Growth", x="Month", y ="Population")
g1

# Notice that we converted year to a factor so that it would
#get a discrete color scale. That scale was named by using scale_color_discrete(
#name="Year"). The-axis was formatted to have commas using
#scale_y_continuous(labels=comma)

#THEMES IN GGPLOTS  USING GGTHEMES LIBRARY
library(ggthemes)
#Build a plot and store it in g2
g2 <- ggplot(diamonds, aes(x=carat, y=price)) + geom_point(aes(color=color))

#Apply a few themes 
g2 + theme_economist() + scale_colour_economist()
g2 + theme_excel() + scale_colour_excel()
g2 + theme_tufte()
g2 + theme_wsj()
